"""`--demo`: a writable copy of the example wardrobe plus a SYNTHETIC 14-day wear history, so the wardrobe grid,
the 'not worn in N days' badges and the rotation can be tried without photographing anything."""
from __future__ import annotations

import json
import shutil
from datetime import date
from pathlib import Path

from .seasons import suggest_season
from .simulate import seed_habit_history

DEMO_SEED = 7
DEMO_HABIT_STRENGTH = 2.5     # a strong habit: a few favourites dominate the 14 days
SAMPLE_DIR = Path(__file__).resolve().parents[2] / "sample_wardrobe"


def init_demo(dest, cfg, cache_path="cache/descriptions.json", today: date | None = None,
              sample_dir: Path | None = None, force: bool = False) -> Path:
    """Create `dest`/wardrobe.json (+ photos, + history.json) unless it already exists. The synthetic history is built
    from the example pieces' cached model descriptions, so every day is a rule-valid outfit. Returns wardrobe.json."""
    from .service import Stylist
    dest, sample = Path(dest), Path(sample_dir or SAMPLE_DIR)
    target = dest / "wardrobe.json"
    if target.is_file() and not force:
        return target
    dest.mkdir(parents=True, exist_ok=True)
    for f in sample.iterdir():
        if f.suffix.lower() in (".png", ".jpg") or f.name == "descriptions.cache.json":
            shutil.copy2(f, dest / f.name)
    data = json.loads((sample / "wardrobe.json").read_text(encoding="utf-8"))
    data.pop("_readonly", None)
    data["_note"] = "EXAMPLE DATA: synthetic illustrations, not real clothes (writable demo copy)"
    target.write_text(json.dumps(data, indent=2, ensure_ascii=False), encoding="utf-8")
    day = today or date.today()
    # the habit user dresses from the current season room, like the app does
    items = Stylist(cfg, target, cache_path, readonly=True).room(suggest_season(day, None))
    hist, _, _ = seed_habit_history(items, day, 14, DEMO_SEED, strength=DEMO_HABIT_STRENGTH)
    hist.extra = {"_note": "SYNTHETIC history generated by `--demo` (a made-up habit user), not data about anyone"}
    hist.path = dest / "history.json"
    hist.save()
    return target
